# Generated by Django 5.0.7 on 2024-07-14 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cart_totalcost_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdProducts', to=settings.AUTH_USER_MODEL),
        ),
    ]
